#!/bin/bash

if [[ $1 != [0-9].[0-9][0-9] ]]; then
  echo Wrong version format. Expected: d.dd
  exit;
fi

# Update version info
# NB: streaming to a temp file. The "-i" option in sed doesn't seem to work.
sed {s/version\ =\ [0-9]\.[0-9][0-9]/version\ =\ $1/} dsss.conf > dsss.conf.tmp
sed {s/VERSION\ =\ \"[0-9]\.[0-9][0-9]\"/VERSION\ =\ \"$1\"/} src/main.d > main.d.tmp
mv dsss.conf.tmp dsss.conf
mv main.d.tmp src/main.d

PREFIX="./build/openquran."
LINDIR="${PREFIX}$1_linux"
WINDIR="${PREFIX}$1_windows"
SRCDIR="${PREFIX}$1_src"

# Convert Unix newlines to Windows newlines
function unix2win
{
  sed {s/$/\\r/} $*
}
# Calls the Windows version of dmd with wine.
function windmd
{
  wine ~/bin/dmd.exe $*
}

# Build Windows binary.
if [[ -s ~/bin/dmd.exe ]] ; then
  rm -rf $WINDIR
  mkdir $WINDIR
  windmd src/*.d -release -O -inline -odwinobj -ofquran
  cp quran.exe $WINDIR
  unix2win COPYING > $WINDIR/License.txt
  unix2win CHANGELOG > $WINDIR/Changelog.txt
else
  echo Warning: Not building Windows package. dmd.exe not found in \~/bin/
fi

# Build Linux binary and source package.
rm -rf $LINDIR $SRCDIR
mkdir $LINDIR $SRCDIR $SRCDIR/src $SRCDIR/doc
dsss build -clean -full -release -O -inline -D -Dd$SRCDIR/doc
cp quran $LINDIR
cp COPYING CHANGELOG $LINDIR
# src
rm $SRCDIR/doc/gcstats.html # generated by rebuild
cp src/*.d $SRCDIR/src
cp AUTHORS COPYING CHANGELOG dsss.conf release.sh $SRCDIR
